docs: PR, Code of Conduct, Contributing, main readme, and Introduction
tadaspetra/conveneapp pull request #77
Opened 2021-11-23 15:16 UTC by tadaspetra

# Description

Add in all the documentation to make it easier for people to get started on the project

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

2021-11-24 15:04 UTC, Afsal102 requested changes

2021-11-24 15:05 UTC, Afsal102 requested changes

2021-11-24 15:05 UTC, Afsal102 commented on .github/PULL_REQUEST_TEMPLATE.MD
> +- [ ] 🗑️ Cho
Chore!

2021-11-24 15:10 UTC, tadaspetra commented on INTRODUCTION.md
> +- pub get
This is just temporary table of contents, or Gaith to use and implement soon

2021-11-25 03:12 UTC, Afsal102 approved these changes

2021-11-25 03:12 UTC, merged