Adding History View
tadaspetra/conveneapp pull request #94
Opened 2021-12-15 22:42 UTC by tadaspetra

# Description
Added a basic history view with similar looking cards to the current books. Also fixed an issue that caused books not to load in.

Fixes #92 
Fixes #56 

## Type of Change

- [ x ] ✨ New feature (non-breaking change which adds functionality)
- [ x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

2021-12-18 13:42 UTC, Afsal102 requested changes

2021-12-18 13:42 UTC, Afsal102 commented on test/apis/firebase/book_test.dart
> +      expect(await bookApiFirebase.getHistoryBooks(), [bookModel]);
Wdyt of splitting this?
final result = await bookApiFirebase.getHistoryBooks();

expect(result,equals([bookModel]))

2021-12-18 13:42 UTC, Afsal102 commented on lib/features/history/view/history_page.dart
> +class HistoryPage extends StatefulWidget {
Any Usage for stateful here? i cant see any usage for stateful widget

2021-12-18 13:42 UTC, Afsal102 commented on lib/features/history/view/history_card.dart
> +              ? Container()
Best usage for this would be `Visibility` widget in my pov

2021-12-18 13:42 UTC, Afsal102 commented on lib/apis/firebase/book.dart
> +  Future<List<BookModel>> getHistoryBooks() async {
Missing functional programming here!
(Either)
+ no proper error handling

2021-12-18 13:42 UTC, Afsal102 commented on lib/features/history/view/history_page.dart
> +    return FutureBuilder(
I would suggest using a controller(State Notifier) here! would be much cleaner and easy to test

2021-12-18 13:42 UTC, Afsal102 commented on lib/features/history/view/history_card.dart
> +                  const SizedBox(
Unnecessary(2) sizedbox this could be 
```dart
const SizedBox(
                    height: 15,
                  ),
```

2021-12-18 13:42 UTC, Afsal102 commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
Usage for network state? Any connectivity plugins

2021-12-18 14:58 UTC, tadaspetra commented on lib/apis/firebase/book.dart
> +  Future<List<BookModel>> getHistoryBooks() async {
I was actually playing around with the Functional Programming part, and got it working.

But getCurrentBooks is not Functional, and since I was using it with a FutureBuilder, the error states and everything was handled there

2021-12-18 14:59 UTC, tadaspetra commented on lib/features/history/view/history_card.dart
> +              ? Container()
Looked into it, but it seems like conditional is optimal https://stackoverflow.com/questions/61852671/visibility-vs-conditional-widget

2021-12-18 14:59 UTC, tadaspetra commented on lib/features/history/view/history_page.dart
> +class HistoryPage extends StatefulWidget {
Good point this can be stateless

2021-12-18 15:00 UTC, tadaspetra commented on test/apis/firebase/book_test.dart
> +      expect(await bookApiFirebase.getHistoryBooks(), [bookModel]);
Hmmm, I think either option is fine, for me this line isn't long enough, where it's easier to read when it's split up, so I think I will keep it this way

2021-12-18 15:01 UTC, tadaspetra commented on lib/features/history/view/history_page.dart
> +    return FutureBuilder(
I will try it out, in that case using StateNotifier, would need to make getHistoryBooks return Either. 

Which I think is the best way

2021-12-18 15:01 UTC, tadaspetra commented on lib/features/history/view/history_card.dart
> +                  const SizedBox(
Yea lol, will remove

2021-12-18 15:03 UTC, tadaspetra commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
I can't remember what this was for, but I was receiving errors for something, and this fixed it. I'll take a look

2021-12-18 15:49 UTC, Afsal102 commented on lib/features/history/view/history_card.dart
> +              ? Container()
in the current use case u r return a container, so i wont have much impact. would be cleaner haa

2021-12-18 15:51 UTC, Afsal102 commented on lib/apis/firebase/book.dart
> +  Future<List<BookModel>> getHistoryBooks() async {
@tadaspetra this would actually break usage, so when u use a controller for this u have to catch it there? i would be unnecessary tests!

i would say we maintain a controller for all the things, so UI should only respond to states emitted by the controller

2021-12-18 15:52 UTC, Afsal102 commented on lib/features/history/view/history_page.dart
> +    return FutureBuilder(
yep! i prefer a MVC or MVVM(not that i know it haa) its properly segregates UI and logic

2021-12-18 15:52 UTC, Afsal102 commented on lib/features/history/view/history_card.dart
> +                  const SizedBox(
haa, just accidentally saw this (::

2021-12-18 15:53 UTC, Afsal102 commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
I think there should be a proper info for what this fixes? wdyt

2021-12-18 15:56 UTC, Afsal102 commented on lib/features/history/view/history_card.dart
> +              ? Container()
@tadaspetra https://api.flutter.dev/flutter/widgets/Visibility-class.html

2021-12-20 09:24 UTC, tadaspetra commented on lib/features/history/view/history_card.dart
> +              ? Container()
In this case we would still be building the Image.network if we used Visibility. I think it's better to default to conditional even if it's a small widget. No need to build more than we need to

2021-12-20 10:17 UTC, tadaspetra commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
i think it's actually not necessary. removed it now good catch

2021-12-20 10:55 UTC, merged