Rating and review
tadaspetra/conveneapp pull request #95
Opened 2021-12-20 14:54 UTC by tadaspetra

# Description
Added ratings and reviews after you finish a book, and those get displayed in the history

Fixes #13 

## Type of Change

- [ x ] ✨ New feature (non-breaking change which adds functionality)
- [ x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

2021-12-21 13:15 UTC, RobertBrunhage requested changes

2021-12-21 13:15 UTC, RobertBrunhage commented on lib/features/dashboard/view/finish_book_page.dart
> +    _reviewFocus.dispose();
Dispose the controller aswell

2021-12-21 13:15 UTC, RobertBrunhage commented on lib/features/dashboard/view/finish_book_page.dart
> +                    rating = newRating;
Any special reason for not calling `setState`?

2021-12-21 13:15 UTC, RobertBrunhage commented on lib/features/dashboard/view/finish_book_page.dart
> +                ),
If this is a typical TextField that will be used, consider breaking it out so you don't have to rewrite the decoration over and over again.

2021-12-21 13:15 UTC, RobertBrunhage commented on lib/features/dashboard/view/finish_book_page.dart
> +                            .showSnackBar(const SnackBar(content: Text("Need to give book a rating")));
Looks like you can add a trailing comma here to make it format better

2021-12-21 13:15 UTC, RobertBrunhage commented on lib/features/dashboard/view/finish_book_page.dart
> +                            .showSnackBar(const SnackBar(content: Text("Please add a review")));
Same here

2021-12-21 13:15 UTC, RobertBrunhage commented on lib/features/dashboard/view/finish_book_page.dart
> +                            );
Is this a `Future`? In that case, what happens if this call fails?

2021-12-21 13:18 UTC, tadaspetra commented on lib/features/dashboard/view/finish_book_page.dart
> +                    rating = newRating;
There is no need. The rating variable is updated for sending to firebase, and the UI is handled by the package

2021-12-21 13:19 UTC, tadaspetra commented on lib/features/dashboard/view/finish_book_page.dart
> +                ),
This is not a typical one. This is just one time extra big one for the reviews

2021-12-21 15:06 UTC, Afsal102 requested changes

2021-12-21 15:06 UTC, Afsal102 commented on test/apis/firebase/book_test.dart
> +      expect((await bookApiFirebase.getHistoryBooks()).getOrElse(() => []), [bookModel]);
this is a bit confusing because the getOrElse wont be tested haa, i think its better right([bookModel]) becuase this is what u intended for, all the usecases/scenarios should be tested!!

2021-12-22 13:02 UTC, tadaspetra commented on lib/features/dashboard/view/finish_book_page.dart
> +                            );
There will be a `failureMessage` that is set in the state object, and the dashboard already reacts to those

2021-12-22 13:04 UTC, tadaspetra commented on lib/features/dashboard/view/finish_book_page.dart
> +class FinishBookPage extends ConsumerStatefulWidget {
I think it's fine for now to keep it in the same one. Since it's part of the dashboard steps. It's like the dialogs except i made it a page since there's more stuff for this one. If it grows to be too big of a file, then we can separate it

2021-12-22 13:25 UTC, tadaspetra commented on test/apis/firebase/book_test.dart
> +      expect((await bookApiFirebase.getHistoryBooks()).getOrElse(() => []), [bookModel]);
`right([bookModel])` doesn't work because for some reason it doesn't see the objects as equal, even though `BookModel` extends `Equatable`

2021-12-23 00:35 UTC, merged